version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "xtendaccounting/simple-react-node-server"
    ports:
      - "8080:8080"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "xtendaccounting/simple-react-node-client"
    ports:
      - "3000:3000"
    links:
      - "server:s"